### ISSUE TITLE
runtime error: index out of range since 0.9.1

### ISSUE THREAD

**Issue by binarious** [mholt/caddy#1061]
This worked in the previous version. It does work with `tls self_signed` though.

#### 1. What version of Caddy are you running (`caddy -version`)?
0.9.1

#### 2. What are you trying to do?
Starting the server.

#### 3. What is your entire Caddyfile?
```text
https://hr.localhost:8000
root /Users/MYUSER/projects/MYAPP/web
gzip

tls /etc/ssl/certs/myssl.crt /etc/ssl/private/myssl.key

rewrite {
  to {path} {path}/ /app_dev.php?{query}
}

fastcgi / 127.0.0.1:9000 php {
  index app_dev.php
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
I just run `caddy` inside the folder with the `Caddyfile`. On OS X 10.11.6

#### 5. What did you expect to see?
The message that the server is running.

#### 6. What did you see instead (give full error messages and/or log)?
```text
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x58dcc0, 0xc42000c100)
    /usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
github.com/mholt/caddy/caddytls.stapleOCSP(0xc4200e3258, 0xc4201ec000, 0x25b, 0x45b, 0x0, 0x0)
    /private/tmp/caddy-20160820-1610-13sjx9c/caddy-0.9.1/src/github.com/mholt/caddy/caddytls/crypto.go:92 +0xa33
github.com/mholt/caddy/caddytls.makeCertificate(0xc4201ec000, 0x25b, 0x45b, 0xc4201b0580, 0x377, 0x577, 0x0, 0x0, 0x0, 0x0, ...)
    /private/tmp/caddy-20160820-1610-13sjx9c/caddy-0.9.1/src/github.com/mholt/caddy/caddytls/certificates.go:187 +0x30c
github.com/mholt/caddy/caddytls.makeCertificateFromDisk(0xc4200f4200, 0x18, 0xc4200f4240, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /private/tmp/caddy-20160820-1610-13sjx9c/caddy-0.9.1/src/github.com/mholt/caddy/caddytls/certificates.go:152 +0x126
github.com/mholt/caddy/caddytls.cacheUnmanagedCertificatePEMFile(0xc4200f4200, 0x18, 0xc4200f4240, 0x1a, 0xc4201383c8, 0xc42018e401)
    /private/tmp/caddy-20160820-1610-13sjx9c/caddy-0.9.1/src/github.com/mholt/caddy/caddytls/certificates.go:118 +0x6a
github.com/mholt/caddy/caddytls.setupTLS(0xc4201e8090, 0x4, 0x622cc6)
    /private/tmp/caddy-20160820-1610-13sjx9c/caddy-0.9.1/src/github.com/mholt/caddy/caddytls/setup.go:175 +0x159d
github.com/mholt/caddy.executeDirectives(0xc4201ae4e0, 0x62787b, 0x9, 0x916400, 0x26, 0x26, 0xc4200f43a0, 0x1, 0x1, 0x0, ...)
    /private/tmp/caddy-20160820-1610-13sjx9c/caddy-0.9.1/src/github.com/mholt/caddy/caddy.go:557 +0x597
github.com/mholt/caddy.startWithListenerFds(0x8cb9a0, 0xc4200f6480, 0xc4201ae4e0, 0x0, 0x64, 0x0)
    /private/tmp/caddy-20160820-1610-13sjx9c/caddy-0.9.1/src/github.com/mholt/caddy/caddy.go:455 +0x39a
github.com/mholt/caddy.Start(0x8cb9a0, 0xc4200f6480, 0x8cb9a0, 0xc4200f6480, 0x0)
    /private/tmp/caddy-20160820-1610-13sjx9c/caddy-0.9.1/src/github.com/mholt/caddy/caddy.go:423 +0xff
github.com/mholt/caddy/caddy/caddymain.Run()
    /private/tmp/caddy-20160820-1610-13sjx9c/caddy-0.9.1/src/github.com/mholt/caddy/caddy/caddymain/run.go:108 +0x26b
main.main()
    /private/tmp/caddy-20160820-1610-13sjx9c/caddy-0.9.1/caddy/main.go:13 +0x1b
```

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
- Create self-signed SSL certificate (https://gist.github.com/jessedearing/2351836#file-gistfile1-sh)
- Use the above `Caddyfile`.
- Start caddy in the folder.

**Comment by mholt** [comment]
I saw this the other day on the [forum](https://forum.caddyserver.com/t/0-9-1-corrupt-gzip/495/5?u=matt) - this happens when the certificate has no names in it. Which is... useless to Caddy.

Anyway, this is already fixed on master with c75ee0000e1677737e0f05efe8de4c101814b848. Feel free to build from source and it should work again.
