### ISSUE TITLE
Large files crash caddy

### ISSUE THREAD

**Issue by OmgImAlexis** [mholt/caddy#1380]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
caddy 0.9.4

### 2. What are you trying to do?
Upload 1GB+ files through proxy

### 3. What is your entire Caddyfile?
Replaced domain with `example.com`
```text
seafile.example.com {
    tls xo@example.com
    proxy / 192.168.1.150:8000 {
        transparent
    }
    gzip
    log stdout
    errors stdout
}

seafile.example.com/seafhttp {
    proxy / 192.168.1.150:8082 {
        transparent
    }
    rewrite /seafhttp {
        regexp (.*)
        to     {1}
    }
    gzip
    log stdout
    errors stdout
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy -quic -conf /etc/Caddyfile`

### 5. What did you expect to see?
Caddy not crash

### 6. What did you see instead (give full error messages and/or log)?
```

goroutine 123182 [select]:
net/http.(*persistConn).writeLoop(0xc420572000)
	/usr/local/go/src/net/http/transport.go:1646 +0x3bd
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1063 +0x50e

goroutine 125405 [IO wait]:
net.runtime_pollWait(0x2ad7d2fc0318, 0x72, 0x12)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420546840, 0x72, 0xc4205e4820, 0xc420010170)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420546840, 0x2a76ee0, 0xc420010170)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4205467e0, 0xc42033d000, 0x1000, 0x1000, 0x0, 0x2a76ee0, 0xc420010170)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4204c2040, 0xc42033d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
github.com/mholt/caddy/caddyhttp/httpserver.(*gracefulConn).Read(0xc42023f060, 0xc42033d000, 0x1000, 0x1000, 0x1d3fd80, 0x0, 0x2ad7d2fc0ac0)
	<autogenerated>:47 +0x6b
crypto/tls.(*block).readFromUntil(0xc420522960, 0x2ad7d2fc0ac0, 0xc42023f060, 0x5, 0xc42023f060, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:476 +0x91
crypto/tls.(*Conn).readRecord(0xc4203a0000, 0x1f54e17, 0xc4203a0108, 0xc4205e4de0)
	/usr/local/go/src/crypto/tls/conn.go:578 +0xc4
crypto/tls.(*Conn).Read(0xc4203a0000, 0xc4203163f8, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1113 +0x116
io.ReadAtLeast(0x2ad7d2fc0b78, 0xc4203a0000, 0xc4203163f8, 0x9, 0x9, 0x9, 0xc4205e4cb0, 0x0, 0x20)
	/usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x2ad7d2fc0b78, 0xc4203a0000, 0xc4203163f8, 0x9, 0x9, 0xc4205e4f10, 0xc420410000, 0xc4205e4eb0)
	/usr/local/go/src/io/io.go:325 +0x58
net/http.http2readFrameHeader(0xc4203163f8, 0x9, 0x9, 0x2ad7d2fc0b78, 0xc4203a0000, 0x0, 0x0, 0xc4205e4f14, 0x2)
	/usr/local/go/src/net/http/h2_bundle.go:779 +0x7b
net/http.(*http2Framer).ReadFrame(0xc4203163c0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1001 +0xa4
net/http.(*http2serverConn).readFrames(0xc4205518c0)
	/usr/local/go/src/net/http/h2_bundle.go:3312 +0xa9
created by net/http.(*http2serverConn).serve
	/usr/local/go/src/net/http/h2_bundle.go:3402 +0x301

goroutine 123118 [IO wait, 22 minutes]:
net.runtime_pollWait(0x2ad7d2ffa738, 0x72, 0xa)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4201ba060, 0x72, 0xc420597478, 0xc420010170)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4201ba060, 0x2a76ee0, 0xc420010170)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4201ba000, 0xc420284c00, 0x400, 0x400, 0x0, 0x2a76ee0, 0xc420010170)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42009c010, 0xc420284c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
github.com/mholt/caddy/caddyhttp/httpserver.(*gracefulConn).Read(0xc42023e060, 0xc420284c00, 0x400, 0x400, 0x1d3fd80, 0x0, 0x2ad7d2fc0ac0)
	<autogenerated>:47 +0x6b
crypto/tls.(*block).readFromUntil(0xc420559530, 0x2ad7d2fc0ac0, 0xc42023e060, 0x5, 0xc42023e060, 0xc420410c18)
	/usr/local/go/src/crypto/tls/conn.go:476 +0x91
crypto/tls.(*Conn).readRecord(0xc4203aa000, 0x1f54e17, 0xc4203aa108, 0x1)
	/usr/local/go/src/crypto/tls/conn.go:578 +0xc4
crypto/tls.(*Conn).Read(0xc4203aa000, 0xc4202c7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1113 +0x116
net/http.(*connReader).Read(0xc420465ea0, 0xc4202c7000, 0x1000, 0x1000, 0x0, 0x42a2ec, 0xc420597940)
	/usr/local/go/src/net/http/server.go:586 +0x144
bufio.(*Reader).fill(0xc4200a9320)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadSlice(0xc4200a9320, 0xa, 0x0, 0x1e, 0x0, 0x33, 0x0)
	/usr/local/go/src/bufio/bufio.go:330 +0xb5
bufio.(*Reader).ReadLine(0xc4200a9320, 0xc4203145a0, 0xf0, 0xf0, 0x1de8f40, 0x53af23, 0x2b58e68)
	/usr/local/go/src/bufio/bufio.go:359 +0x37
net/textproto.(*Reader).readLineSlice(0xc420522bd0, 0xc420597a98, 0xc420597a98, 0x40fa28, 0xf0, 0x1de8f40)
	/usr/local/go/src/net/textproto/reader.go:55 +0x5e
net/textproto.(*Reader).ReadLine(0xc420522bd0, 0xc4203145a0, 0x4544f0, 0xc420287500, 0xc420597b68)
	/usr/local/go/src/net/textproto/reader.go:36 +0x2f
net/http.readRequest(0xc4200a9320, 0x0, 0xc4203145a0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:793 +0xa5
net/http.(*conn).readRequest(0xc42044e100, 0x2a86da0, 0xc4205b80c0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:765 +0x10d
net/http.(*conn).serve(0xc42044e100, 0x2a86da0, 0xc4205b80c0)
	/usr/local/go/src/net/http/server.go:1532 +0x3d3
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Not too sure, this has never happened before.

**Comment by mholt** [comment]
You should upgrade to the latest version of Caddy. :wink: I think it fixes this.

**Comment by OmgImAlexis** [comment]
Unless you fixed the plugin building I can't as it was hanging like I told you on Twitter. 😞

**Comment by mholt** [comment]
Did you try? AFAIK it's working.

**Comment by OmgImAlexis** [comment]
Looks like it's working now. I'll see if it fixes the issue.
