### ISSUE TITLE
Caddy with QUIC = ownCloud, phpMyAdmin and Mail-login impossible

### ISSUE THREAD

**Issue by Henrocker** [mholt/caddy#1390]
### 1. What version of Caddy are you running (`caddy -version`)?

*UPDATE:* Caddy 0.9.5 (+dc6c986 Mi Feb 01 17:27:47 UTC 2017)

### 2. What are you trying to do?

Trying to log into my ownCloud, PhpMyAdmin and rainLoop Webmail Account

### 3. What is your entire Caddyfile?
```text
https://henrock.net {

	tls /etc/caddy/ssl/1_ecc1_henrock.net_bundle.crt /etc/caddy/ssl/2_ecc1.henrock.net.key {

		protocols	tls1.0 tls1.2
		curves		p521 p384 p256

	}

	gzip {

		ext *
		level 4

	}

	fastcgi / unix:/run/php/php7.0-fpm.sock php {

		root		/etc/caddy/html/henrock.net

	}

	header / {
    
		X-XSS-Protection "1; mode=block"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Strict-Transport-Security "max-age=15768000; includeSubdomains; preload;"
		Server "henrock-caddy"

	}

	errors {

		log /etc/caddy/log/error.log
		404 /etc/caddy/errdoc/404.html # Not Found
		500 /etc/caddy/errdoc/500.html # Internal Server Error

	}

		root /etc/caddy/html/henrock.net
		ext .html .htm .php
		log /etc/caddy/log/access.log

}

https://www.henrock.net {

	tls /etc/caddy/ssl/1_ecc1_henrock.net_bundle.crt /etc/caddy/ssl/2_ecc1.henrock.net.key {

		protocols	tls1.0 tls1.2
		curves		p521 p384 p256

	}

	gzip {

		ext *
		level 4

	}

	fastcgi / unix:/run/php/php7.0-fpm.sock php {

		root		/etc/caddy/html/henrock.net

	}

	header / {
    
		X-XSS-Protection "1; mode=block"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Strict-Transport-Security "max-age=15768000; includeSubdomains; preload;"
		Server "henrock-caddy"

	}

	errors {

		log /etc/caddy/log/error.log
		404 /etc/caddy/errdoc/404.html # Not Found
		500 /etc/caddy/errdoc/500.html # Internal Server Error

	}

		root /etc/caddy/html/henrock.net
		ext .html .htm .php
		log /etc/caddy/log/access.log

}

https://blog.henrock.net {

	tls /etc/caddy/ssl/1_ecc1_henrock.net_bundle.crt /etc/caddy/ssl/2_ecc1.henrock.net.key {

		protocols	tls1.0 tls1.2
		curves		p521 p384 p256

	}

	gzip {

		ext *
		level 4

	}

	fastcgi / unix:/run/php/php7.0-fpm.sock php {

		root		/etc/caddy/html/blog.henrock.net

	}

	header / {
    
		X-XSS-Protection "1; mode=block"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Strict-Transport-Security "max-age=15768000; includeSubdomains; preload;"
		Server "henrock-caddy"

	}

	errors {

		log /etc/caddy/log/error.log
		404 /etc/caddy/errdoc/404.html # Not Found
		500 /etc/caddy/errdoc/500.html # Internal Server Error

	}

		root /etc/caddy/html/blog.henrock.net
		ext .html .htm .php
		log /etc/caddy/log/access.log

}

https://sql.henrock.net {

	tls /etc/caddy/ssl/1_ecc1_henrock.net_bundle.crt /etc/caddy/ssl/2_ecc1.henrock.net.key {

		protocols	tls1.0 tls1.2
		curves		p521 p384 p256

	}

	gzip {

		ext *
		level 4

	}

	fastcgi / unix:/run/php/php7.0-fpm.sock php {

		root		/etc/caddy/html/sql.henrock.net

	}

	header / {
    
		X-XSS-Protection "1; mode=block"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Strict-Transport-Security "max-age=15768000; includeSubdomains; preload;"
		Server "henrock-caddy"

	}

	errors {

		log /etc/caddy/log/error.log
		404 /etc/caddy/errdoc/404.html # Not Found
		500 /etc/caddy/errdoc/500.html # Internal Server Error

	}

		root /etc/caddy/html/sql.henrock.net
		ext .html .htm .php
		log /etc/caddy/log/access.log

}

https://cloud.henrock.net {

	tls /etc/caddy/ssl/1_ecc1_henrock.net_bundle.crt /etc/caddy/ssl/2_ecc1.henrock.net.key {

		protocols	tls1.0 tls1.2
		curves		p521 p384 p256

	}

	gzip {

		ext *
		level 4

	}

	fastcgi / unix:/run/php/php7.0-fpm.sock php {

		root		/etc/caddy/html/cloud.henrock.net

	}
	
	rewrite {
        r ^/index.php/.*$
        to /index.php?{query}
    }

    redir /.well-known/carddav /remote.php/carddav 301
    redir /.well-known/caldav /remote.php/caldav 301

    rewrite {
	
        r ^/remote.php/(webdav|caldav|carddav|dav)(\/?)$
        to /remote.php/{1}
		
    }

    rewrite {
	
        r ^/remote.php/(webdav|caldav|carddav|dav)/(.+?)(\/?)$
        to /remote.php/{1}/{2}
		
    }

    rewrite {
	
        r  ^/(?:\.htaccess|data|config|db_structure\.xml|README)
        to status 403
		
    }
	
	header / {
    
		Strict-Transport-Security "max-age=15768000; includeSubdomains; preload;"
		Server "henrock-caddy"

	}

	errors {

		log /etc/caddy/log/error.log
		404 /etc/caddy/errdoc/404.html # Not Found
		500 /etc/caddy/errdoc/500.html # Internal Server Error

	}

		root /etc/caddy/html/cloud.henrock.net
		ext .html .htm .php
		log /etc/caddy/log/access.log

}

https://postfix.henrock.net {

	tls /etc/caddy/ssl/1_ecc1_henrock.net_bundle.crt /etc/caddy/ssl/2_ecc1.henrock.net.key {

		protocols	tls1.0 tls1.2
		curves		p521 p384 p256

	}

	gzip {

		ext *
		level 4

	}

	fastcgi / unix:/run/php/php7.0-fpm.sock php {

		root		/etc/caddy/html/postfix.henrock.net

	}

	header / {
    
		X-XSS-Protection "1; mode=block"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Strict-Transport-Security "max-age=15768000; includeSubdomains; preload;"
		Server "henrock-caddy"

	}

	errors {

		log /etc/caddy/log/error.log
		404 /etc/caddy/errdoc/404.html # Not Found
		500 /etc/caddy/errdoc/500.html # Internal Server Error

	}

		root /etc/caddy/html/postfix.henrock.net
		ext .html .htm .php
		log /etc/caddy/log/access.log

}

https://mail.henrock.net {

	tls /etc/caddy/ssl/1_ecc1_henrock.net_bundle.crt /etc/caddy/ssl/2_ecc1.henrock.net.key {

		protocols	tls1.0 tls1.2
		curves		p521 p384 p256

	}

	gzip {

		ext *
		level 4

	}

	fastcgi / unix:/run/php/php7.0-fpm.sock php {

		root		/etc/caddy/html/mail.henrock.net

	}

	header / {
    
		X-XSS-Protection "1; mode=block"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Strict-Transport-Security "max-age=15768000; includeSubdomains; preload;"
		Server "henrock-caddy"

	}

	errors {

		log /etc/caddy/log/error.log
		404 /etc/caddy/errdoc/404.html # Not Found
		500 /etc/caddy/errdoc/500.html # Internal Server Error

	}

		root /etc/caddy/html/mail.henrock.net
		ext .html .htm .php
		log /etc/caddy/log/access.log

}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

screen ./caddy -conf /etc/caddy/caddy.cf -cpu 2 -log /etc/caddy/log/access.log -quic

### 5. What did you expect to see?

I can log into my accounts on the above sites.

### 6. What did you see instead (give full error messages and/or log)?

- At owncloud: Zugriff verboten, CSRF check failed (in english: Access prohibited, CSRF check failed),

- At phpmyadmin: Site simply reloads when trying to login without any error.

- At Rainloop webinterface: Unbekannter Fehler (in english: unknown error)

When I turn off QUIC by removing the `-quic` Parameter, every login works!!

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Set up an owncloud and enable QUIC when starting the caddy web server. Then try to log in.

**Comment by Gazler** [comment]
I can confirm I had the same issue trying to log in to an Elixir application earlier. The error was:

panic: interface conversion: io.ReadCloser is struct { io.Reader; io.Closer }, not *h2quic.requestBody

```
goroutine 36 [running]:
panic(0x9ca1c0, 0xc4200fae80)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest.func1(0xc4201da160, 0xc420564190, 0xc4200b9590, 0x0, 0xd1e3a0, 0xc420100820)
	/home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:193 +0x17c
created by github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest
	/home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:202 +0x628

```

**Comment by tw4452852** [comment]
This issue should be fix by [this](https://github.com/lucas-clemente/quic-go/issues/405). Please build caddy with the latest quic-go to confirm. Thanks.

**Comment by Henrocker** [comment]
For @Gazler,  the patch from @marten-seemann should work, as his server crashes with POST requests over QUIC, but for me, as you can see above, i recompiled it yesterday, where the fix already existed! So my server does not crash when handling POST Requests.
But I still experience these symptoms I explained above.

**Comment by Gazler** [comment]
I can confirm that the latest dev build doesn't have the issue I reported anymore. Sorry for piggybacking on your issue @Henrocker - I thought it was the same thing.

**Comment by marten-seemann** [comment]
@Henrocker: I can't reproduce this. Please provide us a minimal working example.

**Comment by Henrocker** [comment]
Hi @marten-seemann, 

You could reproduce this by installing an owncloud behind a caddy webserver, with php7. 0-fpm and use QUIC parameter for Caddy, then you wont be able to login at the owncloud login.

**Comment by marten-seemann** [comment]
@Henrocker, I used *php-fpm* and it works. I have no idea how owncloud works.

**Comment by Henrocker** [comment]
@marten-seemann, Can you please somehow let me see how you reproduced the problem?

**Comment by marten-seemann** [comment]
I set up a fastcgi with this line in my Caddyfile

`fastcgi / 127.0.0.1:9000 php`

And then I use an HTML form
```html
<form action="test.php" method="post">
  <input name="val" type="text" value="Lorem ipsum">
  <input type="submit">
</form>
```

that gets posted to `test.php`, where I do a
```php
var_dump($_POST);
```

**Comment by Henrocker** [comment]
Can it be that no login is possible at my server when QUIC enabled, because I use a unix socket for php `unix:/run/php/php7.0-fpm.sock`?

**Comment by coderobe** [comment]
Your latest assumption would be a configuration error on your site though, not an issue with Caddy.
I've got a very similar setup running and i can't reproduce any of the symptoms you're experiencing either.

**Comment by Henrocker** [comment]
Guess, I will leave this issue closed for now, as I am working on a better solution and it seems like I messed up with some configuration... Sorry for the noise.
