### ISSUE TITLE
Panic in OCSP Checking 

### ISSUE THREAD

**Issue by Catofes** [mholt/caddy#1514]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.5

### 2. What are you trying to do?
Normal run caddy.

### 3. What is your entire Caddyfile?
```text
https://atom.catofes.com, https://quark.catofes.com, {
        tls /etc/ssl/nginx/catofes.com.crt /etc/ssl/nginx/catofes.com.key
        root /home/wwwroot/its.pku.edu.cn/
        gzip
        proxy /connect 127.0.0.1:8000 {
                transparent
        }
        status 204 /generate_204
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
CMD ["/usr/app/caddy","-log","stdout","-agree=true","-conf=/usr/app/Caddyfile/Caddyfile"] in Docker.

### 5. What did you expect to see?
Normal run

### 6. What did you see instead (give full error messages and/or log)?
```
2017/03/13 05:40:33 [INFO] Scanning for stale OCSP staples
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4e8787]

goroutine 6 [running]:
panic(0xcf7a20, 0xc42000e030)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/mholt/caddy/caddytls.UpdateOCSPStaples()
        /tmp/custombuild_1385_247495840/src/github.com/mholt/caddy/caddytls/maintain.go:237 +0x767
github.com/mholt/caddy/caddytls.maintainAssets(0xc420064600)
        /tmp/custombuild_1385_247495840/src/github.com/mholt/caddy/caddytls/maintain.go:54 +0x30f
created by github.com/mholt/caddy/caddytls.init.2
        /tmp/custombuild_1385_247495840/src/github.com/mholt/caddy/caddytls/maintain.go:18 +0x58
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
I'm not sure. Maybe use a self cert can reproduce that. 

I found that caddy always panic with error of OCSP staples like:
```
2017/03/13 05:40:33 [INFO] Scanning for stale OCSP staples
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4e8787]

goroutine 6 [running]:
panic(0xcf7a20, 0xc42000e030)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/mholt/caddy/caddytls.UpdateOCSPStaples()
        /tmp/custombuild_1385_247495840/src/github.com/mholt/caddy/caddytls/maintain.go:237 +0x767
github.com/mholt/caddy/caddytls.maintainAssets(0xc420064600)
        /tmp/custombuild_1385_247495840/src/github.com/mholt/caddy/caddytls/maintain.go:54 +0x30f
created by github.com/mholt/caddy/caddytls.init.2
        /tmp/custombuild_1385_247495840/src/github.com/mholt/caddy/caddytls/maintain.go:18 +0x58
```

So I add some code in maintain.go for debug:
```
		err := stapleOCSP(&cert, nil)
		if err != nil {
			if cert.OCSP != nil {
				// if there was no staple before, that's fine; otherwise we should log the error
				log.Printf("[ERROR] Checking OCSP: %v", err)
			}
			continue
		}
		if err == nil {
			log.Printf("[DEBUG] stapleOCSP error. %v", cert.Names)
			log.Println(err)
		}
		// By this point, we've obtained the latest OCSP response.
		// If there was no staple before, or if the response is updated, make
		// sure we apply the update to all names on the certificate.
		log.Printf("[DEBUG] OCSP for %v", cert.Names)
		if cert.OCSP == nil {
			log.Printf("[DEBUG] %v has no OSCP.", cert.Names)
		}
		if lastNextUpdate.IsZero() || lastNextUpdate != cert.OCSP.NextUpdate {
			log.Printf("[INFO] Advancing OCSP staple for %v from %s to %s",
				cert.Names, lastNextUpdate, cert.OCSP.NextUpdate)
			for _, n := range cert.Names {
				updated[n] = ocspUpdate{rawBytes: cert.Certificate.OCSPStaple, parsed: cert.OCSP}
			}
		}
```
And I found that caddy failed at handling the cert I give.  Here is the output:
```
2017/03/13 12:49:10 [INFO] Scanning for stale OCSP staples
2017/03/13 12:49:11 [DEBUG] stapleOCSP error. [*.catofes.com catofes.com ]
2017/03/13 12:49:11 <nil>
2017/03/13 12:49:11 [DEBUG] OCSP for [*.catofes.com catofes.com ]
2017/03/13 12:49:11 [DEBUG] [*.catofes.com catofes.com ] has no OSCP.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x817636]

goroutine 6 [running]:
github.com/mholt/caddy/caddytls.UpdateOCSPStaples()
        /home/herbertqiao/Documents/gocode/src/github.com/mholt/caddy/caddytls/maintain.go:244 +0x8c6
github.com/mholt/caddy/caddytls.maintainAssets(0xc420062480)
        /home/herbertqiao/Documents/gocode/src/github.com/mholt/caddy/caddytls/maintain.go:54 +0x2f2
created by github.com/mholt/caddy/caddytls.init.2
        /home/herbertqiao/Documents/gocode/src/github.com/mholt/caddy/caddytls/maintain.go:18 +0x58
```
The cert is a valid cert and you can get it from https://catofes.com.
![image](https://cloud.githubusercontent.com/assets/3324513/23854985/f1abc6e4-07c1-11e7-8e4f-db98ce75ed76.png)

I think check if cert.OSCP is nil before print the log can easily solve the bug.

**Comment by tobya** [comment]
@Catofes Great issue report thank you.

**Comment by mholt** [comment]
@Catofes Indeed, this was very helpful. I've pushed a fix to master. Can you try it out now?
