### ISSUE TITLE
Markdown template parser "crashes with concurrent map writes"

### ISSUE THREAD

**Issue by harshavardhana** [mholt/caddy#1908]
### 1. What version of Caddy are you using (`caddy -version`)?
v0.10.6

### 2. What are you trying to do?
Rendering markdown

```
Oct 10 14:47:56  caddy[5948]: fatal error: concurrent map writes
Oct 10 14:47:56  caddy[5948]: goroutine 31477 [running]:
Oct 10 14:47:56  caddy[5948]: runtime.throw(0xbed593, 0x15)
Oct 10 14:47:56  caddy[5948]: #011/root/.gimme/versions/go1.8.3.linux.amd64/src/runtime/panic.go:596 +0x95 fp=0xc42127a150 sp=0xc42127a130
Oct 10 14:47:56  caddy[5948]: runtime.mapassign(0xb14560, 0xc4216817a0, 0xc4225797c0, 0x4)
Oct 10 14:47:56  caddy[5948]: #011/root/.gimme/versions/go1.8.3.linux.amd64/src/runtime/hashmap.go:499 +0x667 fp=0xc42127a1f0 sp=0xc42127a150
Oct 10 14:47:56  caddy[5948]: text/template.(*Template).associate(0xc4225797c0, 0xc4225797c0, 0xc420ae3f00, 0x4, 0x10af3e01, 0xc42127a360)
Oct 10 14:47:56  caddy[5948]: #011/root/.gimme/versions/go1.8.3.linux.amd64/src/text/template/template.go:223 +0xa2 fp=0xc42127a240 sp=0xc42127a1f0
Oct 10 14:47:56  caddy[5948]: text/template.(*Template).AddParseTree(0xc4225797c0, 0xc4229d1c58, 0x4, 0xc420ae3f00, 0x0, 0x0, 0x0)
Oct 10 14:47:56  caddy[5948]: #011/root/.gimme/versions/go1.8.3.linux.amd64/src/text/template/template.go:128 +0x110 fp=0xc42127a2a0 sp=0xc42127a240
Oct 10 14:47:56  caddy[5948]: text/template.(*Template).Parse(0xc4225797c0, 0xc423cd6600, 0x12b8, 0x14b8, 0xc423cd6600, 0x12b8)
Oct 10 14:47:56  caddy[5948]: #011/root/.gimme/versions/go1.8.3.linux.amd64/src/text/template/template.go:204 +0x1f0 fp=0xc42127a3a8 sp=0xc42127a2a0
Oct 10 14:47:56  caddy[5948]: github.com/mholt/caddy/caddyhttp/markdown.SetTemplate(0xc4207fba80, 0xc4202ca2d8, 0x4, 0xc420acd9e0, 0x28, 0x895b01, 0xc4208352\
00)
Oct 10 14:47:56  caddy[5948]: #011/root/go/src/github.com/mholt/caddy/caddyhttp/markdown/template.go:70 +0x3dc fp=0xc42127a420 sp=0xc42127a3a8
Oct 10 14:47:56  caddy[5948]: github.com/mholt/caddy/caddyhttp/markdown.execTemplate(0xc421623380, 0xc4202ca3f0, 0xb, 0xc4202ca2d8, 0x4, 0x0, 0x0, 0x0, 0xc42\
12d93e0, 0xc4212d9590, ...)
Oct 10 14:47:56  caddy[5948]: #011/root/go/src/github.com/mholt/caddy/caddyhttp/markdown/template.go:45 +0x332 fp=0xc42127a5c8 sp=0xc42127a420
Oct 10 14:47:56  caddy[5948]: github.com/mholt/caddy/caddyhttp/markdown.(*Config).Markdown(0xc421623380, 0xc42199ff45, 0x4, 0xf419a0, 0xc4208214c0, 0x0, 0x0,\
 0x0, 0xf437a0, 0xc4204dec00, ...)
Oct 10 14:47:56  caddy[5948]: #011/root/go/src/github.com/mholt/caddy/caddyhttp/markdown/process.go:91 +0x658 fp=0xc42127a830 sp=0xc42127a5c8
Oct 10 14:47:56  caddy[5948]: github.com/mholt/caddy/caddyhttp/markdown.Markdown.ServeHTTP(0x7fff42e63f32, 0x14, 0xf437a0, 0xc4204dec00, 0xf42da0, 0xc420ff1a\
a0, 0xc420821760, 0x1, 0x1, 0xf49120, ...)
Oct 10 14:47:56  caddy[5948]: #011/root/go/src/github.com/mholt/caddy/caddyhttp/markdown/markdown.go:143 +0x709 fp=0xc42127aaf8 sp=0xc42127a830
Oct 10 14:47:56  caddy[5948]: github.com/mholt/caddy/caddyhttp/markdown.(*Markdown).ServeHTTP(0xc42185ba90, 0xf49120, 0xc4202ca1c0, 0xc420ae2800, 0x411900, 0\
x10, 0xb5f6c0)
Oct 10 14:47:56  caddy[5948]: #011<autogenerated>:1 +0x9d fp=0xc42127ab80 sp=0xc42127aaf8
Oct 10 14:47:56  caddy[5948]: github.com/ops/repost.(*repostHandler).ServeHTTP(0xc422867680, 0xf49120, 0xc4202ca1c0, 0xc420ae2800, 0xc421938000, 0xc42127ac40\
, 0x8c3300)
Oct 10 14:47:56  caddy[5948]: #011/root/go/src/github.com/ops/repost/module.go:145 +0x1ac fp=0xc42127abd8 sp=0xc42127ab80
Oct 10 14:47:56  caddy[5948]: github.com/mholt/caddy/caddyhttp/internalsrv.Internal.ServeHTTP(0xf40960, 0xc422867680, 0xc4202404e0, 0x2, 0x2, 0xf484e0, 0xc42\
1938080, 0xc420ae2800, 0x80, 0x0, ...)
Oct 10 14:47:56  caddy[5948]: #011/root/go/src/github.com/mholt/caddy/caddyhttp/internalsrv/internal.go:46 +0x12b fp=0xc42127ac60 sp=0xc42127abd8
Oct 10 14:47:56  caddy[5948]: github.com/mholt/caddy/caddyhttp/internalsrv.(*Internal).ServeHTTP(0xc420ff1ad0, 0xf484e0, 0xc421938080, 0xc420ae2800, 0x0, 0x0\
, 0xc420c561c0)
```

### 3. What is your entire Caddyfile?
Cannot be posted at the moment. 

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
/usr/local/bin/caddy -conf=/etc/caddy/Caddyfile.prod -root=/home/www/
```

### 5. Please paste any relevant HTTP request(s) here.
Not sure

### 6. What did you expect to see?
No crash

### 7. What did you see instead (give full error messages and/or log)?
Crashes rarely

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Not sure

**Comment by francislavoie** [comment]
Just to narrow things down, could you try `0.10.10`, i.e. the latest version? I just looked through the changelog to see if anything touched markdown since `0.10.6` and I don't see anything at first glance, but it's usually a fair thing to do.

**Comment by francislavoie** [comment]
Based on the error log, seems like the error happens here: https://github.com/mholt/caddy/blob/3390862918f5ed0d147d7f45de6e4f29b4ef8f53/caddyhttp/markdown/template.go#L70

Called from https://github.com/mholt/caddy/blob/3390862918f5ed0d147d7f45de6e4f29b4ef8f53/caddyhttp/markdown/template.go#L45

(referencing an old commit to get the right line numbers because they changed since a recent release where all the files had a header comment added)

**Comment by tw4452852** [comment]
@francislavoie 

Yes, concurrent parsing template isn't allowed according to `text/template` doc: 

> Once parsed, a template may be executed safely in parallel

I have uploaded a fix, it should work.

**Comment by francislavoie** [comment]
Thanks @tw4452852 😄
