### ISSUE TITLE
 crash: invalid memory address or nil pointer dereference on disk full

### ISSUE THREAD

**Issue by ncw** [mholt/caddy#2041]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.10.10 (non-commercial use only)

### 7. What did you see instead (give full error messages and/or log)?

When the disk got full caddy crashed with a nil pointer deref...

```
Feb 21 16:00:24 example.com caddy[19791]: 2018/02/21 16:00:24 [INFO] Scanning for stale OCSP staples
Feb 21 16:00:24 example.com caddy[19791]: 2018/02/21 16:00:24 [ERROR] Checking OCSP: unable to write OCSP staple file for [slack-invite.rclone.org]: write /etc/ssl/caddy/ocsp/slack-invite.rclone.org-5f08d61a: no space left on device
Feb 21 16:00:24 example.com caddy[19791]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 21 16:00:24 example.com caddy[19791]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x801bdf]
Feb 21 16:00:24 example.com caddy[19791]: goroutine 6 [running]:
Feb 21 16:00:24 example.com caddy[19791]: github.com/mholt/caddy/caddytls.DeleteOldStapleFiles()
Feb 21 16:00:24 example.com caddy[19791]: src/github.com/mholt/caddy/caddytls/maintain.go:323 +0x1df
Feb 21 16:00:24 example.com caddy[19791]: github.com/mholt/caddy/caddytls.maintainAssets(0xc42005c180)
Feb 21 16:00:24 example.com caddy[19791]: src/github.com/mholt/caddy/caddytls/maintain.go:76 +0x1df
Feb 21 16:00:24 example.com caddy[19791]: created by github.com/mholt/caddy/caddytls.init.1
Feb 21 16:00:24 example.com caddy[19791]: src/github.com/mholt/caddy/caddytls/maintain.go:32 +0x4e
Feb 21 16:00:24 example.com systemd[1]: caddy.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by mholt** [comment]
Huh, interesting. Do you know what made the disk full? (Was it in the .caddy folder?) Just want to be sure there's not something else going on.

**Comment by ncw** [comment]
No it was another process that filled the disk - nothing to do with caddy....

Caddy has crashed again after I have emptied the disk 5 or 10 mins after restarting it.

I guess I need to clean something out?

```
Feb 21 17:18:02 example.com caddy[24104]: 2018/02/21 17:18:02 [INFO] Scanning for stale OCSP staples
Feb 21 17:18:02 example.com caddy[24104]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 21 17:18:02 example.com caddy[24104]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x801bdf]
Feb 21 17:18:02 example.com caddy[24104]: goroutine 6 [running]:
Feb 21 17:18:02 example.com caddy[24104]: github.com/mholt/caddy/caddytls.DeleteOldStapleFiles()
Feb 21 17:18:02 example.com caddy[24104]: src/github.com/mholt/caddy/caddytls/maintain.go:323 +0x1df
Feb 21 17:18:02 example.com caddy[24104]: github.com/mholt/caddy/caddytls.maintainAssets(0xc42005c180)
Feb 21 17:18:02 example.com caddy[24104]: src/github.com/mholt/caddy/caddytls/maintain.go:76 +0x1df
Feb 21 17:18:02 example.com caddy[24104]: created by github.com/mholt/caddy/caddytls.init.1
Feb 21 17:18:02 example.com caddy[24104]: src/github.com/mholt/caddy/caddytls/maintain.go:32 +0x4e
Feb 21 17:18:02 example.com systemd[1]: caddy.service: main process exited, code=exited, status=2/INVALIDARGUMENT


```

**Comment by mholt** [comment]
Aha. The code leading up to the line of the panic is:

```go
# in for loop
resp, err := ocsp.ParseResponse(ocspBytes, nil)
if err != nil {
	// contents are invalid; delete it
	err = os.Remove(stapleFile)
	if err != nil {
		log.Printf("[ERROR] Purging corrupt staple file %s: %v", stapleFile, err)
	}
}
if time.Now().After(resp.NextUpdate) {  # line 323 - PANIC
```

There's no `continue` inside the `if err != nil` check. I'll add that and push it in a moment. Thanks for the report.

**Comment by ncw** [comment]
Great - thanks!  From the look of the code my caddy will be OK now I think as I saw it had deleted the file in question and re-created it.

**Comment by mwl** [comment]
We just had the following error with 0.11.4
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x47817e]
goroutine 12474847930 [running]:
bufio.(*Writer).Available(...)
        /usr/local/go/src/bufio/bufio.go:592
bufio.(*Writer).WriteString(0x0, 0xe4372f, 0x19, 0xc01c385c20, 0x509430, 0x6b5c3f)
        /usr/local/go/src/bufio/bufio.go:673 +0x7e
net/http.(*expectContinueReader).Read(0xc00c90e600, 0xc005b67000, 0x812, 0x1000, 0x0, 0xffffffffffffffff, 0x0)
        /usr/local/go/src/net/http/server.go:889 +0x166
io.(*teeReader).Read(0xc00c90e780, 0xc005b67000, 0x812, 0x1000, 0x2, 0x1, 0xc00e6e5b70)
        /usr/local/go/src/io/io.go:535 +0x55
github.com/mholt/caddy/caddyhttp/limits.(*maxBytesReader).Read(0xc007866780, 0xc005b67000, 0x812, 0x1000, 0x408bdb, 0xc00001c000, 0xd3f5c0)
        /tmp/gopath_02-22-0906.228675989/src/github.com/mholt/caddy/caddyhttp/limits/handler.go:74 +0x89
net/http.transferBodyReader.Read(0xc009007360, 0xc005b67000, 0x812, 0x1000, 0xd69220, 0xc00e6e5c01, 0x0)
        /usr/local/go/src/net/http/transfer.go:62 +0x56
io.(*LimitedReader).Read(0xc00f28d940, 0xc005b67000, 0x1000, 0x1000, 0x0, 0x0, 0x5)
        /usr/local/go/src/io/io.go:448 +0x63
bufio.(*Writer).ReadFrom(0xc007867340, 0xf622e0, 0xc00f28d940, 0x7fb4b31ba140, 0xc007867340, 0xc000044f01)
        /usr/local/go/src/bufio/bufio.go:707 +0xe4
io.copyBuffer(0xf61420, 0xc007867340, 0xf622e0, 0xc00f28d940, 0x0, 0x0, 0x0, 0xd76aa0, 0x1, 0xc00f28d940)
        /usr/local/go/src/io/io.go:388 +0x303
io.Copy(0xf61420, 0xc007867340, 0xf622e0, 0xc00f28d940, 0xc0003b0f00, 0x0, 0x1)
        /usr/local/go/src/io/io.go:364 +0x5a
net/http.(*transferWriter).writeBody(0xc009007360, 0xf61420, 0xc007867340, 0x2, 0x2)
        /usr/local/go/src/net/http/transfer.go:362 +0x5b8
net/http.(*Request).write(0xc00d5ce700, 0xf61420, 0xc007867340, 0x0, 0xc0053fa270, 0xc00c90f8a0, 0x0, 0x0)
        /usr/local/go/src/net/http/request.go:645 +0x6e8
net/http.(*persistConn).writeLoop(0xc006265440)
        /usr/local/go/src/net/http/transport.go:1888 +0x1b8
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1339 +0x966
```

I don't know if it's related or I should create another issue?
