### ISSUE TITLE
Caddy long running crash

### ISSUE THREAD

**Issue by wenerme** [mholt/caddy#2189]
### 1. What version of Caddy are you using (`caddy -version`)?

```
docker run --rm -it wener/caddy:full -version
Caddy 0.10.12 (unofficial)
```

### 2. What are you trying to do?
Nothing, found caddy down this morning.

### 3. What is your entire Caddyfile?
Proxy only, with wildcard(pdns provider) and grpc(with insecure_skip_verify)

### 7. What did you see instead (give full error messages and/or log)?

```
2018/05/30 01:18:11 http: TLS handshake error from 110.110.110.110:60844: EOF
2018/05/30 01:18:23 http: TLS handshake error from 110.110.110.110:32784: EOF
2018/05/30 01:18:31 http: TLS handshake error from 110.110.110.110:32846: EOF
2018/05/30 01:18:35 http: TLS handshake error from 110.110.110.110:32880: EOF
2018/05/30 01:18:41 http: TLS handshake error from 110.110.110.110:32930: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8f148c]

goroutine 3075971 [running]:
github.com/mholt/caddy/vendor/golang.org/x/net/http2.(*pipe).Write(0xc420d8e8e8, 0xc420c62dc0, 0x28, 0x13c, 0x0, 0x0, 0x0)
	/go/src/github.com/mholt/caddy/vendor/golang.org/x/net/http2/pipe.go:85 +0xec
github.com/mholt/caddy/vendor/golang.org/x/net/http2.(*clientConnReadLoop).processData(0xc420a93fb0, 0xc420a2f260, 0xc420a2f260, 0x0)
	/go/src/github.com/mholt/caddy/vendor/golang.org/x/net/http2/transport.go:1740 +0x2a0
github.com/mholt/caddy/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc420a93fb0, 0x1e06378, 0xc420a9ffb0)
	/go/src/github.com/mholt/caddy/vendor/golang.org/x/net/http2/transport.go:1377 +0x423
github.com/mholt/caddy/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc4201a9ba0)
	/go/src/github.com/mholt/caddy/vendor/golang.org/x/net/http2/transport.go:1269 +0x76
created by github.com/mholt/caddy/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/go/src/github.com/mholt/caddy/vendor/golang.org/x/net/http2/transport.go:534 +0x651
```

**Comment by wenerme** [comment]
I found `proxy: Fixed file descriptor leak` in 0.11.0 release note, is this the same case ?

**Comment by mholt** [comment]
Can you please fill out the issue template? We're unable to help without that information.

> I found proxy: Fixed file descriptor leak in 0.11.0 release note, is this the same case ?

Nope.

**Comment by wenerme** [comment]
Same exception again

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8f148c]

goroutine 71756 [running]:
github.com/mholt/caddy/vendor/golang.org/x/net/http2.(*pipe).Write(0xc420379568, 0xc420ac05a0, 0x28, 0x55, 0x0, 0x0, 0x0)
	/go/src/github.com/mholt/caddy/vendor/golang.org/x/net/http2/pipe.go:85 +0xec
github.com/mholt/caddy/vendor/golang.org/x/net/http2.(*clientConnReadLoop).processData(0xc420710fb0, 0xc4207be390, 0xc4207be390, 0x0)
	/go/src/github.com/mholt/caddy/vendor/golang.org/x/net/http2/transport.go:1740 +0x2a0
github.com/mholt/caddy/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc420710fb0, 0x1e06378, 0xc420460fb0)
	/go/src/github.com/mholt/caddy/vendor/golang.org/x/net/http2/transport.go:1377 +0x423
github.com/mholt/caddy/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc42062f520)
	/go/src/github.com/mholt/caddy/vendor/golang.org/x/net/http2/transport.go:1269 +0x76
created by github.com/mholt/caddy/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/go/src/github.com/mholt/caddy/vendor/golang.org/x/net/http2/transport.go:534 +0x651
```

**Comment by mholt** [comment]
Hmm. Can you please fill out the whole issue template please?

**Comment by neil88** [comment]
I had the same problem, anyone can tell me how to fix it

**Comment by francislavoie** [comment]
@neil88 please give us more details, this was closed because we couldn't track down the issue due to not enough information.
