### ISSUE TITLE
Caddy crash due to "invalid memory address or nil pointer dereference" within quic module

### ISSUE THREAD

**Issue by wusatosi** [mholt/caddy#2426]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.1 (non-commercial use only)

### 2. What are you trying to do?
Host static website using caddy with quic enabled

### 3. What is your entire Caddyfile?
```text
www.kcibald.com

root ./root
gzip

header / {
	Strict-Transport-Security "max-age=31536000;"
	X-Frame-Options "DENY"
	X-Content-Type-Options "nosniff"
	X-XSS-Protection "1; mode=block"
	Content-Security-Policy "default-src 'none'; script-src 'self' data: 'unsafe-inline' 'unsafe-eval' *.kcibald.com kcibald.com cdn.jsdelivr.net/gh/ProjectFK/; object-src 'none'; style-src 'self' data: 'unsafe-inline' *.kcibald.com kcibald.com cdn.jsdelivr.net/gh/ProjectFK/; img-src *; media-src *; frame-src *.kcibald.com kcibald.com; font-src 'self' data: *.kcibald.com kcibald.com cdn.jsdelivr.net/gh/ProjectFK/; connect-src 'self' data: *.kcibald.com kcibald.com"	
}

errors {
	404 ./404/index.html
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -quic

Centos 7

### 5. Please paste any relevant HTTP request(s) here.

it crashed, but I don't know what request caused it, this crash only appear randomly 

( I think since it is within "quic-go/internal/crypto.(*certChain).getCertForSNI" it would not help if I can reproduce this without byte level package infomation)

### 6. What did you expect to see?

Site working well and uses quic protocol

### 7. What did you see instead (give full error messages and/or log)?

Crash twice in 20 min

log:
```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8b734c]

goroutine 162 [running]:
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto.(*certChain).getCertForSNI(0xc00000c6b8, 0xc000431c34, 0x9, 0xc00040bea0, 0x14207a34, 0xe69c9502e9c5abeb)
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_chain.go:66 +0x6c
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto.(*certChain).GetLeafCert(0xc00000c6b8, 0xc000431c34, 0x9, 0xc000000000, 0xc000431c00, 0x9, 0xc00040bf90, 0x10)
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_chain.go:51 +0x43
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetupServer).handleMessage(0xc0002f5e00, 0xc00016d080, 0x410, 0x51f, 0xc0004455f0, 0x1, 0xc00030a700, 0xc0002f3000)
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup_server.go:162 +0x18f
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetupServer).HandleCryptoStream(0xc0002f5e00, 0x45bad6, 0xbc5650)
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup_server.go:119 +0x21a
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go.(*session).run.func1(0xc0001a0a00)
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/session.go:452 +0x3a
created by github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go.(*session).run
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/session.go:451 +0x8a
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

I'm unable to reproduce this crash consistently, my site is underdevelopment, [there is only one place holder page](https://www.kcibald.com) and an [404 page](https://www.kcibald.com/404), and I suspect this crash has nothing to do with how the request appears.

**Comment by wusatosi** [comment]
Should I report this to [quic-go library](https://github.com/lucas-clemente/quic-go) as well?

**Comment by wusatosi** [comment]
This happened twice, this is the previous crash
```text
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8b734c]

goroutine 162 [running]:
github.c/tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_chain.go:66 +0x6c0bea0, 0x14207a34, 0xe69c9502e9c5abeb)
github.c/tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_chain.go:51 +0x43000, 0xc000431c00, 0x9, 0xc00040bf90, 0x10)
github.c/tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup_server.go:162 +0x18fxc0004455f0, 0x1, 0xc00030a700, 0xc0002f3000)
github.c/tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup_server.go:119 +0x21a
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go.(*session).run.func1(0xc0001a0a00)
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/session.go:452 +0x3a
created by github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go.(*session).run
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/session.go:451 +0x8a
```

**Comment by marten-seemann** [comment]
Duplicate of #2346.

**Comment by wusatosi** [comment]
beside disabling quic, can I bypass this problem?

**Comment by wusatosi** [comment]
```text
goroutine 208 [running]:
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto.(*certChain).getCertForSNI(0xc00000c6c8, 0xc0000314b0, 0xb, 0xc000153ea0, 0xf8a29d3e, 0x7370f0951878ec18)
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_chain.go:66 +0x6c
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto.(*certChain).GetLeafCert(0xc00000c6c8, 0xc0000314b0, 0xb, 0xc000000000, 0xc000031400, 0xb, 0xc000153f90, 0x10)
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_chain.go:51 +0x43
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetupServer).handleMessage(0xc0000e0a00, 0xc00016c000, 0x410, 0x51d, 0xc0001a8090, 0x1, 0x0, 0x0)
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup_server.go:162 +0x18f
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetupServer).HandleCryptoStream(0xc0000e0a00, 0xbf0870, 0x0)
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup_server.go:119 +0x21a
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go.(*session).run.func1(0xc00010c200)
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/session.go:452 +0x3a
created by github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go.(*session).run
        /tmp/gopath_11-29-2027.663245520/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/session.go:451 +0x8a
```text
Same crash happened three minutes ago
