### ISSUE TITLE
panic: *filter.responseWriterWrapper is not a flusher

### ISSUE THREAD

**Issue by STaRDoGG** [mholt/caddy#2643]
Caddy v1.0.0 in Abiosoft's Docker container (PHP version + several added plugins)

I'm getting the error in the title after attempting to load several reverse proxies. After the error Caddy restarts itself each time.

Here's a log of it happening after trying to load up 3 different reverse proxies. Any idea what's causing it?

```
(NOTE: Tried loading Organizr here ...)

Activating privacy features... done.
2019/06/11 18:45:43 [INFO][cache:0xc0001976d0] Started certificate maintenance routine

Serving HTTPS on port 2015
https://subdomain1.mysite.rocks:2015
https://subdomain2.mysite.rocks:2015

2019/06/11 18:45:43 [INFO] Serving https://subdomain1.mysite.rocks:2015
2019/06/11 18:45:43 [INFO] Serving https://subdomain2.mysite.rocks:2015

Serving HTTP on port 80
http://subdomain1.mysite.rocks
http://subdomain2.mysite.rocks

2019/06/11 18:45:43 [INFO] Serving http://subdomain1.mysite.rocks
2019/06/11 18:45:43 [INFO] Serving http://subdomain2.mysite.rocks
2019/06/11 18:45:43 [INFO] Blocking Command "php-fpm7 " with ID 5988322f-b33a-4f4f-9b01-df93e88d65d2

172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/bootstrap/dist/css/bootstrap.min.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/switchery/dist/switchery.min.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/jquery-wizard-master/css/wizard.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/jquery-wizard-master/libs/formvalidation/bootstrap.min.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/Magnific-Popup-master/dist/magnific-popup.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/datatables/jquery.dataTables.min.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/bootstrap-colorpicker-sliders/bootstrap.colorpickersliders.min.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/calendar/dist/fullcalendar.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/jquery-wizard-master/libs/formvalidation/formValidation.min.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/dropzone-master/dist/dropzone.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/moment/moment-timezone.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/js/bowser.min.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/css-chart/css-chart.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/jquery-wizard-master/dist/jquery-wizard.min.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/custom-select/custom-select.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/custom-select/custom-select.min.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/js/jquery.slimscroll.js HTTP/2.0" 200 1762
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/js/jquery-lang.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/owl.carousel/owl.theme.default.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/js/clipboard.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/js/lazyload.min2.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/js/jasny-bootstrap.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/js/js.cookie.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/js/cbpFWTabs.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/hover/hover-min.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/owl.carousel/owl.carousel.min.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/multiselect/css/multi-select.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/js/jquery.serializeToJSON.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/bootstrap-select/bootstrap-select.min.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/styleswitcher/jQuery.style.switcher.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/jquery-wizard-master/libs/formvalidation/formValidation.min.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/ace/mode-css.js HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/css/animate.css HTTP/2.0" 304 0
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/bootstrap/dist/js/bootstrap.min.js HTTP/2.0" 200 9861
172.17.0.1 - - [11/Jun/2019:18:46:27 +0000] "GET /organizrdoc/plugins/bower_components/bootstrap-select/bootstrap-select.min.js HTTP/2.0" 304 0
panic: *filter.responseWriterWrapper is not a flusher

goroutine 891 [running]:
github.com/mholt/caddy/caddyhttp/httpserver.(*ResponseWriterWrapper).Flush(0xc0001be1c0)
	/go/pkg/mod/github.com/mholt/caddy@v1.0.0/caddyhttp/httpserver/responsewriterwrapper.go:44 +0xc5
github.com/mholt/caddy/caddyhttp/proxy.(*maxLatencyWriter).flushLoop(0xc00027c3f0)
	/go/pkg/mod/github.com/mholt/caddy@v1.0.0/caddyhttp/proxy/reverseproxy.go:770 +0xa8
created by github.com/mholt/caddy/caddyhttp/proxy.(*ReverseProxy).copyResponse
	/go/pkg/mod/github.com/mholt/caddy@v1.0.0/caddyhttp/proxy/reverseproxy.go:509 +0x14e
exit status 2

(NOTE: Caddy restarted itself. Tried loading Ombi here ...)

172.17.0.1 - - [11/Jun/2019:18:49:16 +0000] "GET /ombidoc HTTP/2.0" 200 1192
panic: *filter.responseWriterWrapper is not a flusher

goroutine 67 [running]:
github.com/mholt/caddy/caddyhttp/httpserver.(*ResponseWriterWrapper).Flush(0xc00003e560)
	/go/pkg/mod/github.com/mholt/caddy@v1.0.0/caddyhttp/httpserver/responsewriterwrapper.go:44 +0xc5
github.com/mholt/caddy/caddyhttp/proxy.(*maxLatencyWriter).flushLoop(0xc000168990)
	/go/pkg/mod/github.com/mholt/caddy@v1.0.0/caddyhttp/proxy/reverseproxy.go:770 +0xa8
created by github.com/mholt/caddy/caddyhttp/proxy.(*ReverseProxy).copyResponse
	/go/pkg/mod/github.com/mholt/caddy@v1.0.0/caddyhttp/proxy/reverseproxy.go:509 +0x14e
exit status 2

(NOTE: Caddy restarted itself. Tried loading Medusa here ...)

172.17.0.1 - - [11/Jun/2019:18:55:44 +0000] "GET /medusadoc HTTP/2.0" 302 23
172.17.0.1 - - [11/Jun/2019:18:55:45 +0000] "GET /medusadoc/home/ HTTP/2.0" 200 4214
172.17.0.1 - - [11/Jun/2019:18:55:45 +0000] "GET /medusadoc/css/vender.min.css?221 HTTP/2.0" 200 937
172.17.0.1 - - [11/Jun/2019:18:55:46 +0000] "GET /medusadoc/css/browser.css?221 HTTP/2.0" 200 312
172.17.0.1 - - [11/Jun/2019:18:55:46 +0000] "GET /medusadoc/css/lib/jquery-ui-1.10.4.custom.min.css?221 HTTP/2.0" 200 4491
172.17.0.1 - - [11/Jun/2019:18:55:46 +0000] "GET /medusadoc/css/lib/jquery.qtip-2.2.1.min.css?221 HTTP/2.0" 200 2263
172.17.0.1 - - [11/Jun/2019:18:55:46 +0000] "GET /medusadoc/css/print.css?221 HTTP/2.0" 200 189
172.17.0.1 - - [11/Jun/2019:18:55:46 +0000] "GET /medusadoc/css/themed.css?221 HTTP/2.0" 200 4867
172.17.0.1 - - [11/Jun/2019:18:55:46 +0000] "GET /medusadoc/css/country-flags.css?221 HTTP/2.0" 200 1512
panic: *filter.responseWriterWrapper is not a flusher

goroutine 2716 [running]:
github.com/mholt/caddy/caddyhttp/httpserver.(*ResponseWriterWrapper).Flush(0xc00003f570)
	/go/pkg/mod/github.com/mholt/caddy@v1.0.0/caddyhttp/httpserver/responsewriterwrapper.go:44 +0xc5
github.com/mholt/caddy/caddyhttp/proxy.(*maxLatencyWriter).flushLoop(0xc00029acc0)
	/go/pkg/mod/github.com/mholt/caddy@v1.0.0/caddyhttp/proxy/reverseproxy.go:770 +0xa8
created by github.com/mholt/caddy/caddyhttp/proxy.(*ReverseProxy).copyResponse
	/go/pkg/mod/github.com/mholt/caddy@v1.0.0/caddyhttp/proxy/reverseproxy.go:509 +0x14e
exit status 2
```

**Comment by mholt** [comment]
Thanks for the issue and providing the log, but we'll need more information. Please fill out the issue template so we can help you and we can re-open this.
