### ISSUE TITLE
Caddy throws when using hugo

### ISSUE THREAD

**Issue by matthewp** [mholt/caddy#389]
Using 0.8.

With this config:

```
http://localhost:8888 {
  root public
  hugo {
    args "--theme=hyde"
  }
}

```

I get this error:

```
Activating privacy features... done.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x2dfe21]

goroutine 1 [running]:
github.com/hacdias/caddy-hugo/utils.Run(0x208e8d2c0)
	/home/caddy/go/src/github.com/hacdias/caddy-hugo/utils/utils.go:178 +0x2b1
github.com/hacdias/caddy-hugo.Setup(0x208eea100, 0x0, 0x0, 0x0)
	/home/caddy/go/src/github.com/hacdias/caddy-hugo/hugo.go:26 +0x7d
github.com/mholt/caddy/caddy.loadConfigs(0x89c510, 0x9, 0x2208e4a2a0, 0x208f79050, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/config.go:162 +0x1a8a
github.com/mholt/caddy/caddy.Start(0x2208e4bd50, 0x208f79020, 0x0, 0x0)
	/tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/caddy.go:138 +0x2c3
main.main()
	/tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/main.go:99 +0x5fe

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 9 [chan receive]:
github.com/mholt/caddy/caddy.func·012()
	/tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/sigtrap_posix.go:19 +0x2d9
created by github.com/mholt/caddy/caddy.trapSignalsPosix
	/tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/sigtrap_posix.go:72 +0x25

goroutine 8 [chan receive]:
github.com/mholt/caddy/caddy.func·010()
	/tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/sigtrap.go:31 +0x110
created by github.com/mholt/caddy/caddy.trapSignalsCrossPlatform
	/tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/sigtrap.go:41 +0x25

goroutine 10 [select]:
github.com/mholt/caddy/caddy/letsencrypt.maintainAssets(0x208ee71e0, 0x1, 0x1, 0x0)
	/tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/letsencrypt/maintain.go:34 +0x7cd
created by github.com/mholt/caddy/caddy/letsencrypt.Activate
	/tmp/custombuild_6545_142287504/src/github.com/mholt/caddy/caddy/letsencrypt/letsencrypt.go:146 +0x113a

```

**Comment by mholt** [comment]
This would be good to bring up with @hacdias - open this issue at https://github.com/hacdias/caddy-hugo - thanks!

**Comment by matthewp** [comment]
Ah, sorry about that, posted it here for others who see this issue: https://github.com/hacdias/caddy-hugo/issues/34
