### ISSUE TITLE
Markdown parsing crash

### ISSUE THREAD

**Issue by sakamies** [mholt/caddy#868]
Hi there! I'm not really sure what went wrong, but caddy crashed when rendering a markdown file. I thought that better to report this than not. I haven't been able to reproduce this, sorry. There's nothing crazy in the markdown file, just a couple headings, lists and a ```<p><a href="">...</p>``` combo. I'm running Ubuntu 16 and using a shared dropbox folder as my webroot, if that makes a difference.

#### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.8.3

#### 2. What are you trying to do?

Reload a markdown page, not sure if there was anything out of the ordinary going on.

#### 3. What is your entire Caddyfile?
```text
#www.pumpula.net {
#  redir https://pumpula.net{uri}
#}
localhost:3000, new.pumpula.net {
  root pumpula.net
  gzip
  fastcgi / /var/run/php/php7.0-fpm.sock php
  markdown {
    template template.html
  }

  # Redirect old apps urls to workflower apps
  rewrite {
    regexp ^/p/apps
    to /p/apps/redir
  }
  redir /p/apps/redir http://apps.workflower.fi 301

  rewrite {
    ext    /
    to     /index.php
  }
  rewrite /404 {
    status 404
  }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

Running the command at /var/www
```
su - www-data -s /bin/bash -c 'cd ~/Dropbox && ulimit -n 16000 && caddy -agree -conf="Caddyfile.txt" -email="ville@pumpula.net"' &
```

#### 5. What did you expect to see?

A rendered markdown page.

#### 6. What did you see instead (give full error messages and/or log)?

```
root@pumpula:/var/www# panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x80a6ea]

goroutine 25 [running]:
panic(0xaaf4c0, 0xc82000e0c0)
  /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/mholt/caddy/middleware/markdown.computeDirHash.func1(0xc82026d300, 0x17, 0x0, 0x0, 0x7fa9926b1f18, 0xc82031e840, 0x0, 0x0)
  /tmp/custombuild_5989_337073156/src/github.com/mholt/caddy/middleware/markdown/generator.go:135 +0x5a
path/filepath.walk(0xc820494860, 0xb, 0x7fa9926b1d48, 0xc82011aa90, 0xc82046af40, 0x0, 0x0)
  /usr/local/go/src/path/filepath/path.go:370 +0x415
path/filepath.Walk(0xc820494860, 0xb, 0xc82046af40, 0x0, 0x0)
  /usr/local/go/src/path/filepath/path.go:396 +0xe1
github.com/mholt/caddy/middleware/markdown.computeDirHash(0xc82000fdd0, 0xb, 0x7fa9926b77f8, 0xc820169ea0, 0x7fa9926b7848, 0xc82016de30, 0xc820020160, 0x1, 0x1, 0xc820169eb0, ...)
  /tmp/custombuild_5989_337073156/src/github.com/mholt/caddy/middleware/markdown/generator.go:134 +0x22f
github.com/mholt/caddy/middleware/markdown.(*linkGen).generateLinks(0xc820013590, 0xc82000fdd0, 0xb, 0x7fa9926b77f8, 0xc820169ea0, 0x7fa9926b7848, 0xc82016de30, 0xc820020160, 0x1, 0x1, ...)
  /tmp/custombuild_5989_337073156/src/github.com/mholt/caddy/middleware/markdown/page.go:86 +0x27b
github.com/mholt/caddy/middleware/markdown.generateLinks(0xc82000fdd0, 0xb, 0x7fa9926b77f8, 0xc820169ea0, 0x7fa9926b7848, 0xc82016de30, 0xc820020160, 0x1, 0x1, 0xc820169eb0, ...)
  /tmp/custombuild_5989_337073156/src/github.com/mholt/caddy/middleware/markdown/generator.go:72 +0x1f6
github.com/mholt/caddy/middleware/markdown.GenerateStatic(0xc82000fdd0, 0xb, 0x7fa9926b77f8, 0xc820169ea0, 0x7fa9926b7848, 0xc82016de30, 0xc820020160, 0x1, 0x1, 0xc820169eb0, ...)
  /tmp/custombuild_5989_337073156/src/github.com/mholt/caddy/middleware/markdown/generator.go:23 +0x53
github.com/mholt/caddy/middleware/markdown.Watch.func1()
  /tmp/custombuild_5989_337073156/src/github.com/mholt/caddy/middleware/markdown/watcher.go:16 +0x3c
github.com/mholt/caddy/middleware/markdown.TickerFunc.func1(0xc82031a640, 0xc820328d20, 0xc82019d320)
  /tmp/custombuild_5989_337073156/src/github.com/mholt/caddy/middleware/markdown/watcher.go:33 +0x97
created by github.com/mholt/caddy/middleware/markdown.TickerFunc
  /tmp/custombuild_5989_337073156/src/github.com/mholt/caddy/middleware/markdown/watcher.go:39 +0x7a
```

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

I don't really know. I'll try to help if you have ideas on how. :)

**Comment by mholt** [comment]
Well, this is awkward. :smile: The panicking code was removed from Caddy [months ago](https://github.com/mholt/caddy/pull/762) but hasn't been released yet.

**Comment by sakamies** [comment]
Still parses markdown, but just doesn't crash anymore, right? I love removing code, totally counts. :)

**Comment by mholt** [comment]
Yeah, markdown is still rendered. :) We just took out the static site generation functionality.

I'm gonna close this, but I do sympathize with your situation! Feel free to try the Caddy 0.9 betas as they start rolling out this week.
